### ISSUE TITLE
Jest client Reindex.Build() does not support painless script parameter

### ISSUE THREAD

**Issue by CountCodeula** [searchbox-io/Jest#600] opened 2018-07-12 16:26 UTC
The Reindex.Build() method has a parameter to add in a script object, but does not seem to support Painless, or does not support all types of painless scripts. When I pass in a well-formed Painless script into the Reindex.Build() method:

Script{type=stored, lang='null', idOrCode='set-index-date1', options=null, params={fromDate=2007-01-01, firstArray=first.dataArray, dateCountField=first.rxDatesCount, toDate=2018-08-31, rowKeyField=first.rxRowKey, dateField=first.rxDates, index_occurs=1, rowKey=[1234567]}} 

The response I get back is : 
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[reindex] failed to parse field [script]","line":1,"col":2158}],"type":"parsing_exception","reason":"[reindex] failed to parse field [script]","line":1,"col":2158,"caused_by":{"type":"illegal_argument_exception","reason":"[script] unknown field [type], parser not found"}},"status":400}

"type" is a valid field and ElasticSearch 6.0 it is a required parameter for the Script class.

Is there another way around this issue?

**Comment by musabgelisgen** [comment] 2018-08-06 08:31
The part which caused the error is probably the params field (and could be any other field which itself is a JSON object). The issue is fixed on Jest 6.3.1 (master) and 5.3.4, will be published on next release. Now, scripting accepts both

- a JSON formatted String
- a Map of String and Objects (using nested Map<K,V> objects)

**Closed by musabgelisgen** 2018-08-06 08:31 UTC
