### ISSUE TITLE
SearchResult.getSourceAsObjectList() deprecated - update documentation

### ISSUE THREAD

**Issue by bencarlson** [searchbox-io/Jest#253] opened 2015-11-05 15:27 UTC
While getting started with querying elasticsearch via Jest, I followed the docs, which give this example: 

```java
SearchResult result = client.execute(search);
List<SearchResult.Hit<Article, Void>> hits = searchResult.getHits(Article.class);
// or
List<Article> articles = result.getSourceAsObjectList(Article.class);
```

However, when following this, I noticed this output in my logs: 

```java
<T>getSourceAsObjectList(java.lang.Class<T>) in io.searchbox.core.SearchResult has been deprecated
```

What is the recommended approach to getting a list of domain objects? Use Gson / Jackson?

Thanks,

-Ben

**Comment by kramer** [comment] 2015-11-05 17:30
`getHits` is the recommended approach.

**Comment by bencarlson** [comment] 2015-11-05 21:54
Thanks @kramer ; I've been playing with using getHits() for a few hours now, and I'm struggling to get my results back as my domain objects. Any chance you could update the docs with an example?

**Comment by kramer** [comment] 2015-11-05 21:59
`List<SearchResult.Hit<Article, Void>> hits = searchResult.getHits(Article.class);`

Well the line you quoted is exactly how you get them. What exactly are you having problem with?

**Comment by bencarlson** [comment] 2015-11-05 22:21
I don't get a List<Article> back... I'm not understanding how to get a List<Article> so I can iterate over it. From the source, it looks like I should be able to do: 

List<SearchResult.Hit<Article, Void>> hits = searchResult.getHits(Article.class);
for(SearchResult.Hit hit : hits) {
  Logger.debug("article: " + ((Article)hit.source).title);
}

or something like that, but I keep getting 0 hits back. When I run the same query through getSourceAsObjectList(Article.class)

I get back the number of expected results. Also, in the json, I'm seeing the correct count of hits, and the hit records. Thoughts? I guess I'm going to just use the getSourceAsObjectList() for the short term, and deal with the deprecation in a few weeks when I have more time (haha). Thanks!

**Comment by kramer** [comment] 2015-11-05 22:26
Yup, you definitely should be able to do that, something seems to be wrong if you are getting different results from `getHits` and `getSourceAsObjectList`.

Which version of ES do you have on the server and which version of Jest are you using? Also if possible posting your json and code would be helpful to reproduce the problem.

**Comment by kramer** [comment] 2015-11-12 08:24
Closing as no updates were provided recently. Please feel free to reopen if you feel you have more to add to the issue.

**Closed by kramer** 2015-11-12 08:24 UTC
Labels: question
