### ISSUE TITLE
Search does not support fields selection ?

### ISSUE THREAD

**Issue by cuberri** [searchbox-io/Jest#157] opened 2014-10-27 15:27 UTC
Hi !

I'm giving a try to Jest for some basic search features.

I'm trying to load only some fields from the documents hit by a search request, and get the results as domain objects (incomplete and dirty objects but still objects :))

``` java
@Test
public void testFindWithFieldsShouldReturnHermes() throws Exception {
    // given
    IndexesObjectFactory fact = new IndexesObjectFactory("http://localhost:9200");
    JestClient client = fact.jestClient();

    createIndex("futurama");
    index("futurama", "user", "1", userAsMap("Philip", "Fry", "philip.fry@planetexpress.com", "pfry"));
    index("futurama", "user", "2", userAsMap("Hermes", "Conrad", "hermes.conrad@planetexpress.com", "hconrad"));
    index("futurama", "user", "3", userAsMap("Amy", "Wong", "amy.wong@planetexpress.com", "awong"));

    refresh();

    SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder()
            .fields("login", "email")
            .query(QueryBuilders.queryString("hconrad"));
    Search search = new Search.Builder(searchSourceBuilder.toString())
            .addIndex("futurama")
            .build();

    SearchResult result = client.execute(search);

    // when
    List<User> users = result.getSourceAsObjectList(User.class);

    // then
    assertEquals(1, users.size());
}
```

This test basically creates an index, populates it with some "users", and builds a query which looks like this when serialized :

``` json
{
  "query" : {
    "query_string" : {
      "query" : "hconrad"
    }
  },
  "fields" : [ "login", "email" ]
}
```

The ES cluster's response :

``` json
{
    "took" : 120,
    "timed_out" : false,
    "_shards" : {
        "total" : 4,
        "successful" : 4,
        "failed" : 0
    },
    "hits" : {
        "total" : 1,
        "max_score" : 0.11506981,
        "hits" : [{
                "_index" : "futurama",
                "_type" : "user",
                "_id" : "2",
                "_score" : 0.11506981,
                "fields" : {
                    "login" : ["hconrad"],
                    "email" : ["hermes.conrad@planetexpress.com"]
                }
            }
        ]
    }
}

```

The test fails returning 0 domain object instead of 1. The test is ok when I comment the `fields()` builder's method, which ends up with the following request/reply :

``` json
{
  "query" : {
    "query_string" : {
      "query" : "hconrad"
    }
  }
}
```

ES's response :

``` json
{
    "took" : 163,
    "timed_out" : false,
    "_shards" : {
        "total" : 8,
        "successful" : 8,
        "failed" : 0
    },
    "hits" : {
        "total" : 1,
        "max_score" : 0.11506981,
        "hits" : [{
                "_index" : "futurama",
                "_type" : "user",
                "_id" : "2",
                "_score" : 0.11506981,
                "_source" : {
                    "lastName" : "Conrad",
                    "email" : "hermes.conrad@planetexpress.com",
                    "login" : "hconrad",
                    "firstName" : "Hermes"
                }
            }
        ]
    }
}
```

The thing is Jest seems to extract the document from the path `hits/hits/_source`, which is correct when a request without fields selection is sent to ES but incorrect when fields are set in the query.

Imho, even if the correct path to the document is set (`hits/hits/fields`), the unmarshall process would fail because Jest relies on the Gson lib, which would not handle correctly the mapping JSon array -> String attribute (ES API [returns the field values as arrays](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-fields.html))

Do I miss something ? What is the recommended way to perform such queries with Jest ?

Thanks !

**Comment by tomsen-san** [comment] 2015-02-17 07:12
Hit the same problem yesterday :-) This might make a very nice improvement. I might even volunteer ;-) Anyone up for discussing possible solutions?

**Comment by bartekbp** [comment] 2015-07-13 23:33
Did you consider using [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-request-source-filtering.html)? This seems to solve field selection problem.

**Comment by oravecz** [comment] 2015-08-17 03:14
+1 I am planning on using fields in my queries, and I see that Jest supports that. However, as OP mentioned, there doesn't seem to be a way of deserializing the SearchResult object to access the fields.

A method analogous to getHits(Class) might work, but field names can contain nested results. I think something as simple as results.getFieldAsString(Boolean) would suffice.

**Comment by raunak** [comment] 2015-12-14 22:15
Is this something that has been added/addressed in the new release?

**Comment by kramer** [comment] 2015-12-14 22:25
@raunak No, it was not addressed hence the issue is still open.

**Comment by ryanitus** [comment] 2018-02-21 22:38
I was able to workaround this by using SearchResult.setPathToResult("hits/hits/fields") before calling getHits().

**Closed as completed** 2018-08-08 07:21 UTC
Labels: question
